- name: Remove existing container if it exists
  command: >
    docker rm -f {{ docker_container_name }}
  ignore_errors: yes
  become: true

- name: Remove dangling images
  command: >
    docker image prune -f
  ignore_errors: yes
  become: true

- name: Run the Docker container
  command: >
    docker run -d --name {{ docker_container_name }}
    -p {{ app_port }}:5196
    {{ docker_image_name }}
  become: true
