- name: Pull Docker image from Docker Hub
  ansible.builtin.docker_image:
    name: "{{ docker_image_name }}"
    source: pull

- name: Stop existing container if running
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    state: stopped
  ignore_errors: true

- name: Remove existing container if present
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    state: absent
  ignore_errors: true

- name: Deploy new Docker container
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    ports:
      - "{{ app_port }}:5196"
    restart_policy: always
