- name: Pull Docker image from Docker Hub
  ansible.builtin.docker_image:
    name: "{{ docker_image_name }}"
    source: pull

- name: Stop existing container if running
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    state: stopped
    image: "{{ docker_image_name }}"
  ignore_errors: true

- name: Remove existing container if present
  ansible.builtin.docker_container:
    name: "{{ docker_container_name }}"
    state: absent
  ignore_errors: true

- name: Create application directory
  file:
    path: "/opt/{{app_name}}"
    state: directory
    mode: '0755'

- name: Copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "/opt/{{app_name}}/docker-compose.yml"

- name: Start application with Docker Compose
  command: docker-compose up -d
  args:
    chdir: "/opt/{{app_name}}"
