---
- name: Deploy TodoApi with Docker
  hosts: all
  become: true
  vars:
    docker_image_name: todoapi:latest
    docker_container_name: todoapi_container
    app_source_path: /home/mikky/webapp/TodoApi
    app_port: 5196
  roles:
    - docker
    - todoapi
