---
- name: Deploy TodoApi with Docker
  hosts: all
  become: true
  vars:
    docker_image_name: mikkyms/webapi-aspdotnet
    docker_container_name: webapi-container
    app_port: 5196
  roles:
    - docker
    - todoapi
