---
- name: Deploy TodoApi with Docker
  hosts: all
  become: true
  vars:
    app_name  : "web-api-app"
    docker_image_name: mikkyms/webapi-aspdotnet:2.2
    docker_container_name: webapi-container
    app_port: 5196
  roles:
    - docker
    - stop-container
    - app
    - watchtower
