name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH key
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 192.168.10.56 >> ~/.ssh/known_hosts
        
    # Step 3: Disable sudo password prompt
    - name: Disable sudo password prompt
      run: |
        echo "${USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/99-no-password

    # Step 3: Install Ansible
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    # Step 4: Run Ansible playbook
    - name: Run Ansible playbook
      run: |
        cd ansible
        ansible-playbook -i inventory.yml deploy_todoapi.yml
